#!/bin/bash
# Launch Freeview for an Input Subject
# ------------------------------------------------------------------------------------------
# Default Arguments
# -------------------
hname=$(hostname)
mach=$(machine)
cd ~/..
me=$(whoami)
usrpth=$(pwd)
usrpth=$usrpth/$me
cd $usrpth
d=$(date)

# default user arguments
subjid='bert'

optionstring=''
imgformat=".mgz"

# default freeview loadings
vol=""
bm=""
t1=""
wmv=""
aseg=""

surf=""
pial=""
wms=""
inf=""

editors=''
# ------------------------------------------------------------------------------------------
# Help
show_help() {
cat <<EOF

Usage: ${0##*/} [-h|--help] [-v|--vol] [-s|--surf] [-T1] [-bm|--brainmask]
							[-wmv|--whitemattervol] [-p|--pial] [-wms|--whitemattersurf]
							[-sub|--subjid STRING] [-sd|--subjectsdir STRING]
							[-g|--group STRING] [-imgf|--imgformat STRING]

Launch FreeView for a given subject in a set SUBJECTS_DIR. User may set options to view 
specific volumes or surfaces.

Options :: 

	-h --help 		Displays help
	-v --vol 		Loads volumes (must indicate which volume)
	-s --surf 		Loads surfaces (must indicate which surfs)
	-T1 			Loads intensity normalized T1
	-bm --brainmask 	Loads skull stripped brain mask
	-wmv --whitemattervol	Loads white matter probabalistic volume
	-p --pial 		Loads pial surface
	-wms --whitemattersurf 	Loads white matter surface
	-sub --subjid 		subject name
	-sd  --subjectsdir 	subjects directory (use this to change from default)
	-g 	 --group 	group identifier for subjects with multiple scans (i.e. longitudinal)
	-imgf --imgformat 	Format of volume images (.nii/.nii.gz/.mgz)
			
Example ::

	Load a subject's volumes

		${0##*/} -sub 001 -v -T1 -bm -wmv

	Load a subject's surfaces

		${0##*/} -sub 001 -s -p -wms		

	Load a subject's volumes and surfaces

		${0##*/} -sub 001 -v -s -T1 -bm -wmv -p -wms


Default Behavior ::

		Will show the brainmaks, pial and white surfaces by default for bert.

IMPORTANT !!

	* Program assumes volume image format of .mgz by default (use -imgf option to set format)


EOF
}
# ------------------------------------------------------------------------------------------
# Parse Options
while :; do
    case $1 in
	-h|--help)
	    show_help
	    exit
	    ;;
	-v|--vol)
	    vol="show"
	    t1='show'
	    bm='show'
	    wm='show'
	    aseg='show'
	    ;;
	-surf|--surf)
	    surf="show"
		pial="show"
		wms="show"
		inf="show"	    
	    ;;
	-T1)
	    t1="show"
	    ;;
	-bm|--brainmask)
	    bm="show"
	    ;;
	-bet|--showbets)
		bet="show"
		;;
	-wmv|--whitemattervol)
	    wm="show"
	    ;;
	-aseg|--aseg)
	    aseg="show"
	    ;;	    
	-p|--pial)
	    pial="show"
	    ;;
	-wms|--whitemattersurf)
	    wms="show"
	    ;;
	-inf|--inflated)
	    inf="show"
	    ;;
	-e|--edit)
	    editors='edit'
	    ;;	    	    
	-s|--subjid)
	    if [ -n "$2" ]; then
			subjid=$2
			shift
	    else
			echo "ERROR: -s --subjid requires a non empty option argument.\n" >&2
			exit
	    fi
	    ;;
	-sd|--subjectsdir)
	    if [ -n "$2" ]; then
			SUBJECTS_DIR=$2
			shift
	    else
			echo "ERROR: -sd --subjectsdir requires a non empty option argument.\n" >&2
			exit
	    fi
	    ;;
	-imgf|--imgformat)
	    if [ -n "$2" ]; then
			imgformat=$2
			shift
	    else
			echo "ERROR: -imgf --imgformat requires a non empty option argument.\n" >&2
			exit
	    fi
	    ;;	    
	-?*)
	    printf 'Warn: Unknown option (ignored): %s\n' "%1" >&2
	    ;;
	*)
	    break
    esac

    shift
done
# ------------------------------------------------------------------------------------------
# Begin Script
# ---------------------
# Check if SUBJECTS DIRECTORY exists
if [ ! -d "${SUBJECTS_DIR}" ]; then
    echo "ERROR! Subjects Directory not found:  $SUBJECTS_DIR"
    exit
fi
# Check if loading subject for editing
if [ "${editors}" ]; then
	optionstring=${optionstring}"-c "
	[ ! -d "${SUBJECTS_DIR}/${subjid}/tmp" ] && mkdir -v "${SUBJECTS_DIR}/${subjid}/tmp"
	[ ! -f "${SUBJECTS_DIR}/${subjid}/tmp/control.dat" ] && touch ${SUBJECTS_DIR}/${subjid}/tmp/control.dat
	optionstring=${optionstring}"${SUBJECTS_DIR}/${subjid}/tmp/control.dat "
	vol='show' && t1='show' && bm='show' && wmv='show' && aseg='show'
	surf='show' && pial='show' && wms='show' && inf='show' && bet='show'
fi
# Check if volume flag is set
if [ "${vol}" ]; then
    optionstring=${optionstring}"-v "
    # Check if t1 is indicated
    [ "${t1}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/mri/T1$imgformat "
    # Check if brainmask is indicated
    [ "${bm}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/mri/brainmask$imgformat "
    # Check if Brain Extraction Results is indicated
    [ "${bet}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/mri/brainmask*-bet-[2345].nii* "
    # Check if whitematter is indicated
    [ "${wmv}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/mri/wm$imgformat:colormap=heat:opacity=0.4:visible=0 "
    # Check if aseg is indicated
    [ "${aseg}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/mri/aseg$imgformat:colormap=lut:opacity=0.4:visible=0 "
fi
# Check if surface flag is set
if [ "${surf}" ]; then
    optionstring=$optionstring"-f "
    # Check if pial surface is set
    [ "${pial}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/surf/lh.pial:edgecolor=red $SUBJECTS_DIR/$subjid/surf/rh.pial:edgecolor=red "
    # Check if white matter surface is set
    [ "${wms}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/surf/lh.white:edgecolor=blue $SUBJECTS_DIR/$subjid/surf/rh.white:edgecolor=blue "
    # Check if white matter surface is set
	[ "${inf}" ] && optionstring=$optionstring"$SUBJECTS_DIR/$subjid/surf/lh.inflated:edgecolor=yellow $SUBJECTS_DIR/$subjid/surf/rh.inflated:edgecolor=green "
fi
# Run FreeView with set options
freeview ${optionstring} &
